[2024-03-12T20:00:10.533-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_data.split_data scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-03-12T20:00:10.541-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_data.split_data scheduled__2024-03-12T00:00:00+00:00 [queued]>
[2024-03-12T20:00:10.541-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-12T20:00:10.597-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): split_data> on 2024-03-12 00:00:00+00:00
[2024-03-12T20:00:10.621-0400] {standard_task_runner.py:60} INFO - Started process 397517 to run task
[2024-03-12T20:00:10.629-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'train_data', 'split_data', 'scheduled__2024-03-12T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpjllu2iz8']
[2024-03-12T20:00:10.630-0400] {standard_task_runner.py:88} INFO - Job 83: Subtask split_data
[2024-03-12T20:00:10.708-0400] {task_command.py:423} INFO - Running <TaskInstance: train_data.split_data scheduled__2024-03-12T00:00:00+00:00 [running]> on host DESKTOP-6U7QAQN.
[2024-03-12T20:00:10.813-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@email.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_data' AIRFLOW_CTX_TASK_ID='split_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-12T00:00:00+00:00'
[2024-03-12T20:00:10.815-0400] {logging_mixin.py:188} INFO - /home/ironbong_jr/mlops/project/Group-5-Default-of-Credit-Card-Clients-IE7374/airflow/dags/dataSplit/../data/default of credit card clients.xls
[2024-03-12T20:00:18.408-0400] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 397517. PIDs of all processes in the group: [397517]
[2024-03-12T20:00:18.409-0400] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 397517
[2024-03-12T20:00:18.409-0400] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-12T20:00:28.919-0400] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ironbong_jr/mlops/project/Group-5-Default-of-Credit-Card-Clients-IE7374/airflow/dags/dataSplit/dataSplit.py", line 17, in split
    train_val_data.to_excel(trainpath, index=False)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/core/generic.py", line 2414, in to_excel
    formatter.write(
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 952, in write
    writer._write_cells(
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 486, in _write_cells
    for cell in cells:
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 889, in get_formatted_cells
    for cell in itertools.chain(self._format_header(), self._format_body()):
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 786, in _format_regular_rows
    yield from self._generate_body(coloffset)
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/pandas/io/formats/excel.py", line 877, in _generate_body
    yield CssExcelCell(
  File "/home/ironbong_jr/mlops/project/project/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-12T20:00:28.973-0400] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=train_data, task_id=split_data, execution_date=20240312T000000, start_date=20240313T000010, end_date=20240313T000028
[2024-03-12T20:00:29.011-0400] {standard_task_runner.py:107} ERROR - Failed to execute job 83 for task split_data (Task received SIGTERM signal; 397517)
