[2024-03-13T15:50:43.211-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_data.validate_train manual__2024-03-13T19:50:07.336612+00:00 [queued]>
[2024-03-13T15:50:43.215-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_data.validate_train manual__2024-03-13T19:50:07.336612+00:00 [queued]>
[2024-03-13T15:50:43.215-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-13T15:50:43.232-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): validate_train> on 2024-03-13 19:50:07.336612+00:00
[2024-03-13T15:50:43.239-0400] {standard_task_runner.py:60} INFO - Started process 454199 to run task
[2024-03-13T15:50:43.242-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'train_data', 'validate_train', 'manual__2024-03-13T19:50:07.336612+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpexk3ey7c']
[2024-03-13T15:50:43.243-0400] {standard_task_runner.py:88} INFO - Job 134: Subtask validate_train
[2024-03-13T15:50:43.277-0400] {task_command.py:423} INFO - Running <TaskInstance: train_data.validate_train manual__2024-03-13T19:50:07.336612+00:00 [running]> on host DESKTOP-6U7QAQN.
[2024-03-13T15:50:43.328-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@email.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_data' AIRFLOW_CTX_TASK_ID='validate_train' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T19:50:07.336612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T19:50:07.336612+00:00'
[2024-03-13T15:50:43.329-0400] {train_validate.py:19} WARNING - starting new run
[2024-03-13T15:50:43.337-0400] {train_validate.py:25} INFO - train test split done
[2024-03-13T15:50:43.342-0400] {train_validate.py:35} INFO - training and validation data dunmped as pkl
[2024-03-13T15:50:43.478-0400] {train_validate.py:40} INFO - schema infer done from train data
[2024-03-13T15:50:43.481-0400] {train_validate.py:45} INFO - infered schema store for future use
[2024-03-13T15:50:43.553-0400] {train_validate.py:51} INFO - generate anomalies from test data
[2024-03-13T15:50:43.554-0400] {logging_mixin.py:188} INFO - No anomalies detected in new data
[2024-03-13T15:50:43.554-0400] {train_validate.py:67} INFO - No anomalies detected in new data
[2024-03-13T15:50:43.554-0400] {python.py:202} INFO - Done. Returned value was: None
[2024-03-13T15:50:43.557-0400] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=train_data, task_id=validate_train, execution_date=20240313T195007, start_date=20240313T195043, end_date=20240313T195043
[2024-03-13T15:50:43.578-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T15:50:43.587-0400] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
