[2024-03-13T00:37:48.660-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_data.validate_test manual__2024-03-13T04:37:17.777854+00:00 [queued]>
[2024-03-13T00:37:48.670-0400] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_data.validate_test manual__2024-03-13T04:37:17.777854+00:00 [queued]>
[2024-03-13T00:37:48.671-0400] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-03-13T00:37:48.697-0400] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): validate_test> on 2024-03-13 04:37:17.777854+00:00
[2024-03-13T00:37:48.710-0400] {standard_task_runner.py:60} INFO - Started process 434875 to run task
[2024-03-13T00:37:48.715-0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'predict_data', 'validate_test', 'manual__2024-03-13T04:37:17.777854+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpij2276ks']
[2024-03-13T00:37:48.716-0400] {standard_task_runner.py:88} INFO - Job 121: Subtask validate_test
[2024-03-13T00:37:48.800-0400] {task_command.py:423} INFO - Running <TaskInstance: predict_data.validate_test manual__2024-03-13T04:37:17.777854+00:00 [running]> on host DESKTOP-6U7QAQN.
[2024-03-13T00:37:48.897-0400] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@email.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='predict_data' AIRFLOW_CTX_TASK_ID='validate_test' AIRFLOW_CTX_EXECUTION_DATE='2024-03-13T04:37:17.777854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-13T04:37:17.777854+00:00'
[2024-03-13T00:37:49.260-0400] {logging_mixin.py:188} INFO - No anomalies detected in new data
[2024-03-13T00:37:49.262-0400] {python.py:202} INFO - Done. Returned value was: None
[2024-03-13T00:37:49.273-0400] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=predict_data, task_id=validate_test, execution_date=20240313T043717, start_date=20240313T043748, end_date=20240313T043749
[2024-03-13T00:37:49.373-0400] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-13T00:37:49.402-0400] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
